/* eslint-disable quotes */

// This config defines how the language is displayed in the editor.
export const languageDef = {
  defaultToken: '',
  tokenPostfix: '.ccs',

  keywords: [
    'on',
    'if',
    'if_not',
    'while',
    'while_not',
    'execute',
    'execute_random',
    'execute_period',
    'as',
    'wait',
    'wait_random',
    'loop',
    'loop_period',
    'print',
    'throw',
    'exit',
    'function',
    'module',
    'create',
    'description',
    'config',
    'say',
    'send',
    'notify',
    'playsound',
    'define',
    'drop',
    'teleport',
    'velocity',
    'turn_to',
    'snap_to',
    'damage',
    'switch',
    'swap',
    'input',
    'hold',
    'gui_drop',
    'gui_switch',
    'gui_swap',
    'gui_quickmove',
    'def',
    'desc',
  ],

  operators: [
    '=',
    '>',
    '<',
    '!',
    '~',
    '?',
    '#',
    ':',
    '==',
    '<=',
    '>=',
    '!=',
    '&&',
    '||',
    '++',
    '--',
    '+',
    '-',
    '*',
    '/',
    '&',
    '|',
    '^',
    '%',
  ],

  symbols: /[=><!~?:&|+\-*\/\^%]+/,
  escapes:
    /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,
  digits: /\d+(_+\d+)*/,

  tokenizer: {
    root: [
      [/\/\/\s*/, 'comment.text'],
      [/\/\/\s*(\@[\w-]+)/, ['comment.text', 'comment.author']],
      [
        /\b(on|if|if_not|while|while_not|execute|execute_random|execute_period|as|wait|wait_random|loop|loop_period|print|throw|exit|function|module|create|description|config|say|send|notify|playsound|define|drop|teleport|velocity|turn_to|snap_to|damage|switch|swap|input|hold|gui_drop|gui_switch|gui_swap|gui_quickmove|def|desc)\b/,
        'keyword',
      ],
      [
        /\b([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*)\b/,
        { cases: { '@keywords': 'string', '@default': 'string' } },
      ],
      [/(:\w+|#\w+(-\w+)*)/, 'string2'],
      [
        /[a-zA-Z_]\w*/,
        { cases: { '@keywords': 'keyword', '@default': 'identifier' } },
      ],
      [/\b\d+(_+\d+)*\b/, 'number'],
      [/[{}()\[\]]/, '@brackets'],
      [/@symbols/, { cases: { '@operators': 'delimiter', '@default': '' } }],
      [/"([^"\\]|\\.)*$/, 'string.invalid'],
      [/"/, 'string', '@string'],
      [/'[^\\']'/, 'string'],
      [/(')(@escapes)(')/, ['string', 'string.escape', 'string']],
      [/'/, 'string.invalid'],
    ],
    whitespace: [[/[\s\t\r\n]+/, '']],
    string: [
      [/[^\\"]+/, 'string'],
      [/@escapes/, 'string.escape'],
      [/\\./, 'string.escape.invalid'],
      [/"/, 'string', '@pop'],
    ],
  },
};

// This config defines the editor's behavior.
export const configuration = {
  comments: {},
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')'],
  ],
};

// This defines the color theme of the editor.
export const theme = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment.text', foreground: '6A9955' },
    { token: 'comment.author', foreground: 'FFD700' },
    { token: 'keyword', foreground: 'C586C0' },
    { token: 'identifier', foreground: '9CDCFE' },
    { token: 'delimiter', foreground: 'D4D4D4' },
    { token: 'string', foreground: '4EC9B0' },
    { token: 'string.escape', foreground: '4EC9B0' },
    { token: 'string2', foreground: '569CD6' },
    { token: 'number', foreground: 'B5CEA8' },
    { token: 'brackets', foreground: 'D4D4D4' },
  ],
  colors: {},
};
